### ISSUE TITLE
Error: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url

### ISSUE THREAD

**Issue by tukangcode** [DefamationStation/Retrochat#2]
How to reproduce step
1. Drag Model to Retrochat.exe
2. type anything
3. error visible

Full error 
`HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError(': Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`

**Comment by DefamationStation** [comment]
hiya,

apologies maybe i should clarify in the readme that this is just a UI, it can't run models. 

Run your llama.cpp server as normal in a machine and just point to it's IP using /config host in the UI.
