### ISSUE TITLE
[Featured request] kobold cpp support? 

### ISSUE THREAD

**Issue by tukangcode** [DefamationStation/Retrochat#3]
Hi just want know if you support koboldcpp if that possible. 
Thanks.

**Comment by DefamationStation** [comment]
Hello



Kobold.cpp uses Llama.cpp as it's server so it should work by default, you just need to point the host IP to the correct Port



try running Kobold.cpp, opening Retrochat and run the command /config host 127.0.0.1:5001



I tested it on my machine and it works like that

**Comment by tukangcode** [comment]
Thanks, I'll check it out.
